version: "2"
services:
  db:
    build: ./db/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_webapp
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
  www:
    build: ./www/
    links:
      - db
    volumes:
      - ./www/:/var/www/:rw
      - ./www/webapp/:/var/www/webapp/:rw
  nginx:
    build: ./nginx/
    links:
      - www
    volumes_from:
      - www
    ports:
      - 8080:80
