version: "2.4"
services:
  db:
    build: ./db/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_webapp
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3333:3306"
  www:
    build: ./www/
    volumes:
      - ./www/webapp:/var/www/webapp
  nginx:
    build: ./nginx
    volumes_from:
      - www
    ports:
      - 8080:80
